[2021-01-23 16:17:14] - ERROR    - ['localhost', 'system'] - no such table: omflow_scheduler
[2021-01-23 16:20:44] - ERROR    - ['127.0.0.1', 'admin', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - OmUser matching query does not exist.
Traceback (most recent call last):
  File "E:\programing\qhse-erp\omflow\omuser\views.py", line 113, in checkMultipleLoginAjax
    usersearch = OmUser.objects.get(username=username)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
omuser.models.OmUser.DoesNotExist: OmUser matching query does not exist.
[2021-01-23 16:20:45] - ERROR    - ['127.0.0.1', 'admin', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - 
{'csrfmiddlewaretoken': 'Y2k1xv241om6UHxN1xAGTH08ymPxridT1jkA2T4sXlK1TUJixNGhgYfAc7vR1t7V'}
