[2021-03-16 09:58:17] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 09:58:30] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 09:58:39] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 09:58:45] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 09:58:48] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 09:59:10] - ERROR    - ['127.0.0.1', 'youssri.ahmed', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - OmUser matching query does not exist.
Traceback (most recent call last):
  File "E:\programing\python\qhse-erp\home\aeraeg\python\apps\omflow\omuser\views.py", line 113, in checkMultipleLoginAjax
    usersearch = OmUser.objects.get(username=username)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
omuser.models.OmUser.DoesNotExist: OmUser matching query does not exist.
[2021-03-16 09:59:10] - ERROR    - ['127.0.0.1', 'youssri.ahmed', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - 
{'csrfmiddlewaretoken': 'f60A1x7d4DGVtoQwq3wzxdLvynZNpzGATFIyzaFNP40jOYeJl4xPjckOYPQKaFmZ'}
[2021-03-16 10:01:06] - ERROR    - "GET /service/page/list/ HTTP/1.1" 500 59
[2021-03-16 10:03:53] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 10:05:08] - ERROR    - "POST /accounts/api/multiple-login/check/ HTTP/1.1" 500 59
[2021-03-16 10:06:39] - ERROR    - ['localhost', 'system'] - LDAP error：No module named 'ldap3'
[2021-03-16 10:06:45] - ERROR    - "POST /api/workinfo/load/ HTTP/1.1" 500 59
[2021-03-16 10:06:45] - ERROR    - "POST /api/l-side/load/ HTTP/1.1" 500 59
[2021-03-16 10:08:03] - ERROR    - "POST /accounts/api/multiple-login/check/ HTTP/1.1" 500 59
