[2021-01-26 19:04:41] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - OmUser matching query does not exist.
Traceback (most recent call last):
  File "E:\programing\qhse-erp\omflow\omuser\views.py", line 113, in checkMultipleLoginAjax
    usersearch = OmUser.objects.get(username=username)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
omuser.models.OmUser.DoesNotExist: OmUser matching query does not exist.
[2021-01-26 19:04:41] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - OmUser matching query does not exist.
Traceback (most recent call last):
  File "E:\programing\qhse-erp\omflow\omuser\views.py", line 113, in checkMultipleLoginAjax
    usersearch = OmUser.objects.get(username=username)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
omuser.models.OmUser.DoesNotExist: OmUser matching query does not exist.
[2021-01-26 19:04:41] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - 
{'csrfmiddlewaretoken': 'AOh0S0dkzkUjdgVsmJRoBG8FBGJmeexFEQ6d32W5b0Uvi9tAFbaLWKNI4z0cyRkd'}
[2021-01-26 19:04:42] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - 
{'csrfmiddlewaretoken': 'AOh0S0dkzkUjdgVsmJRoBG8FBGJmeexFEQ6d32W5b0Uvi9tAFbaLWKNI4z0cyRkd'}
[2021-01-26 19:04:50] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - OmUser matching query does not exist.
Traceback (most recent call last):
  File "E:\programing\qhse-erp\omflow\omuser\views.py", line 113, in checkMultipleLoginAjax
    usersearch = OmUser.objects.get(username=username)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\youssri.ahmed.CONTACTGROUP\.conda\envs\omflow\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
omuser.models.OmUser.DoesNotExist: OmUser matching query does not exist.
[2021-01-26 19:04:50] - ERROR    - ['127.0.0.1', '', '/accounts/api/multiple-login/check/', 'checkMultipleLoginAjax'] - 
{'csrfmiddlewaretoken': 'MxtmyqXB8FXXEPa74PODUDj6nRbue62FQzizJsGmKlX9JIIfnh70fHY9QKskyJPd'}
